version: "3.2"

services:
  frontend:
    tty: true
    build: .
    # command: npm run dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - 3000:3000
    # depends_on:
    #   - backend

  backend:
    tty: true
    build: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./server:/app
    ports:
      - 3010:3010
